name: settlement-tunnel

services:
  settlement:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - SSH_PORT=${SSH_PORT}
        - SSH_USER=${SSH_USER}
        - SSH_SUBNET=${SSH_SUBNET}
    restart: always
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    devices:
      - /dev/net/tun
    environment:
      - SSH_PORT=${SSH_PORT}
      - SSH_USER=${SSH_USER}
      - SSH_SUBNET=${SSH_SUBNET}
      - ZT_NETWORK_ID=${ZT_NETWORK_ID}
    ports:
      - "${SSH_PORT}:${SSH_PORT}"
      - "2375:2375"
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .docker/zero-tier:/var/lib/zerotier-one
      - ssh:/home/admin/.ssh
      - ${HOME}/git:/home/${SSH_USER}/git
      - /bin/systemctl:/bin/systemctl
      - /run/systemd/system:/run/systemd/system
      - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket
      - /sys/fs/cgroup:/sys/fs/cgroup
    networks:
      - settlement-network

networks:
  settlement-network:
    driver: bridge

volumes:
  config:
  ssh:
